version: '3'

services:
#  petwise_backend:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - petwise_db
#    container_name: petwise_backend
#    environment:
#      SERVER_PORT: 8080
#      DB_HOST: petwise_db
#      DB_USER: db_user
#      DB_PASSWORD: db_password
#    ports:
#      - "8080:8080"
  petwise_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db_user
      POSTGRES_DB: petwise_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
